AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for the invoke lambda functions

Parameters:
  lambdaARNTemplate:
    Type: String
    Default: 'arn:aws:lambda:us-west-2:957374566417:function:'
  associateLambdaName:
    Type: String
    Default: associatelambda
  batchesLambdaName:
    Type: String
    Default: batcheslambda
  categoriesLambdaName:
    Type: String
    Default: categorieslambda
  batchAssociatesLambdaName:
    Type: String
    Default: batchassociateslambda
  qcWeekLambdaName:
    Type: String
    Default: batchweeklambda
  qcCategoriesLambdaName:
    Type: String
    Default: weekcategorieslambda
  fireBaseLambdaName:
    Type: String
    Default: authorizerlambda

Resources:
  InvokeBatchesLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join ['', [!Ref lambdaARNTemplate, !Ref batchesLambdaName]]
      Principal: apigateway.amazonaws.com

  InvokeCategoriesLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !Join ['', [!Ref lambdaARNTemplate, !Ref categoriesLambdaName]]
      Principal: apigateway.amazonaws.com
  InvokeQCWeekLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join ['', [!Ref lambdaARNTemplate, !Ref qcWeekLambdaName]]
      Principal: apigateway.amazonaws.com
  InvokeQCCategoriesLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !Join ['', [!Ref lambdaARNTemplate, !Ref qcCategoriesLambdaName]]
      Principal: apigateway.amazonaws.com
  InvokeAssociateLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !Join ['', [!Ref lambdaARNTemplate, !Ref associateLambdaName]]
      Principal: apigateway.amazonaws.com

  InvokeBatchAssociatesLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !Join ['', [!Ref lambdaARNTemplate, !Ref batchAssociatesLambdaName]]
      Principal: apigateway.amazonaws.com

  InvokeFirebaseLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !Join ['', [!Ref lambdaARNTemplate, !Ref fireBaseLambdaName]]
      Principal: apigateway.amazonaws.com
