# Make the authorizer lambda from an existingimage
AWSTemplateFormatVersion: 2010-09-09
Description: lambda for Authorizer Group
Resources:
  AuthorizerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          !Join [
            '/',
            [
              !Join [
                '.',
                [
                  !Sub '${AWS::AccountId}',
                  'dkr',
                  'ecr',
                  !Sub '${AWS::Region}',
                  'amazonaws',
                  'com',
                ],
              ],
              'authorizer:latest',
            ],
          ]
      Role: arn:aws:iam::957374566417:role/caliber-mobile-cf
      FunctionName: 'authorizerlambda'
      PackageType: 'Image'
