# Make the WeekCategories lambda from an existingimage
AWSTemplateFormatVersion: 2010-09-09
Description: lambda for WeekCategories Group
Resources:
  WeekCategoriesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          !Join [
            '/',
            [
              !Join [
                '.',
                [
                  !Sub '${AWS::AccountId}',
                  'dkr',
                  'ecr',
                  !Sub '${AWS::Region}',
                  'amazonaws',
                  'com',
                ],
              ],
              'weekcategories:latest',
            ],
          ]
      Role: arn:aws:iam::957374566417:role/caliber-mobile-cf
      FunctionName: 'weekcategorieslambda'
      PackageType: 'Image'
