AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for Batches Group
Resources:
  BatchesLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: batchesLambda
      Role: arn:aws:iam::957374566417:role/caliber-mobile-cf
      Code:
        ImageUri:
          !Join [
            '/',
            [
              !Join [
                '.',
                [
                  !Sub '${AWS::AccountId}',
                  'dkr',
                  'ecr',
                  !Sub '${AWS::Region}',
                  'amazonaws',
                  'com',
                ],
              ],
              'batches:latest',
            ],
          ]
      Timeout: 5
      PackageType: 'Image'
